### ISSUE TITLE
相機顯示問題

### ISSUE THREAD

**Issue by z0furu** [ray00178/RayZhangAlbum#1]
請問是否可以把相機 View，改成可選顯示的嗎～？謝謝

**Comment by ray00178** [comment]
你好，這個部分是可以的! 近期會在調整，感謝您的建議，謝謝

**Comment by ang77305** [comment]
請問AlbumScanner 的 getPhotoAlbum "所有照片" 資料夾的字串,可以改成可以自定義的嗎～謝謝
