### ISSUE TITLE
AlbumScanner 資料夾名稱

### ISSUE THREAD

**Issue by ang77305** [ray00178/RayZhangAlbum#2]
請問AlbumScanner 的 getPhotoAlbum "所有照片" 資料夾的字串,可以改成可以自定義的嗎～謝謝

**Comment by ray00178** [comment]
@ang77305 有看到您的需求，這部分是可以的！但近期較忙故需些許等待時間，跟您說聲抱歉！

**Comment by ray00178** [comment]
@ang77305 已將資料夾的字串，改成自定義了，請更新至1.7.0 謝謝！
